<a href="https://colab.research.google.com/github/prithviratkalkar2304-coder/Prithvi_Ratkalkar/blob/main/Data%20Wrangling/Experiment12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Name:Prithvi Ratkalkar

PRN:25070123165

Batch: ENTC-A1

#Unit 3 - Data Wrangling

#Experiment-12
#To Perform Preprocessing on a dataset and Dealing with Missing Values

In [ ]:
import pandas as pd
import numpy as np
df1=pd.DataFrame({'C1':[11,21,np.nan],'C2':[13,np.nan,np.nan],'C3':[104,250,330]})
df1

     C1    C2   C3
0  11.0  13.0  104
1  21.0   NaN  250
2   NaN   NaN  330

In [ ]:
df1.isna() #Boolean Function

      C1     C2     C3
0  False  False  False
1  False   True  False
2   True   True  False

In [ ]:
df1.notna()

      C1     C2    C3
0   True   True  True
1   True  False  True
2  False  False  True

In [ ]:
df1.isna().sum()  #Columnwise na values

C1    1
C2    2
C3    0
dtype: int64

In [ ]:
df1.dropna() #NaN Rows are dropped(if NaN are present that row is Skipped/deleted)

     C1    C2   C3
0  11.0  13.0  104

In [ ]:
df1.fillna(value='Delfault')

         C1        C2   C3
0      11.0      13.0  104
1      21.0  Delfault  250
2  Delfault  Delfault  330

In [ ]:
df1.fillna(df1.mean()) #Mean values of columns are calculated

     C1    C2   C3
0  11.0  13.0  104
1  21.0  13.0  250
2  16.0  13.0  330

In [ ]:
import pandas as pd
data={
    "Roll No":[101,102,103,104,105],
    "Name":["Prithvi","Akshay","Raj","Diya","Sam"],
    "Age":[20,"-",21,23,"18"],
    "Marks":[89,87,90,'-',95],
    "Department":["CSE","ENTC","it","MECH","cse"],
    "Admission_Date":["01-06-2025","23-03-2025","07-07-2025","14-06-2025","26/10/2025"]
}
df=pd.DataFrame(data)
df

   Roll No     Name Age Marks Department Admission_Date
0      101  Prithvi  20    89        CSE     01-06-2025
1      102   Akshay   -    87       ENTC     23-03-2025
2      103      Raj  21    90         it     07-07-2025
3      104     Diya  23     -       MECH     14-06-2025
4      105      Sam  18    95        cse     26/10/2025

In [ ]:
#Step 2:Replace '-'with NaN to mark the missing values
df.replace("-",np.nan,inplace=True)
#Comvert columns to numeric where needed
df["Age"]=pd.to_numeric(df["Age"],errors='coerce')
df["Marks"]=pd.to_numeric(df["Marks"],errors='coerce')

/tmp/ipykernel_160/1382466715.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace("-",np.nan,inplace=True)

In [ ]:
#Step3: Check the missing values
print("\nMissing Values:")
print(df.isnull().sum())

Missing Values:
Roll No           0
Name              0
Age               1
Marks             1
Department        0
Admission_Date    0
dtype: int64

In [ ]:
#Step4: Fill missing Age with mean
df["Age"].fillna(df["Age"].mean(),inplace=True)
#Fill missing Marks with median
df["Marks"].fillna(df["Marks"].median(),inplace=True)
df

/tmp/ipykernel_160/429987435.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(),inplace=True)
/tmp/ipykernel_160/429987435.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Marks"].fillna(df["Marks"].median(),inplace=True)

   Roll No     Name   Age  Marks Department Admission_Date
0      101  Prithvi  20.0   89.0        CSE     01-06-2025
1      102   Akshay  20.5   87.0       ENTC     23-03-2025
2      103      Raj  21.0   90.0         it     07-07-2025
3      104     Diya  23.0   89.5       MECH     14-06-2025
4      105      Sam  18.0   95.0        cse     26/10/2025

In [ ]:
#Step5: Fix the inconsistent text format
df["Department"]=df["Department"].str.upper()
df

   Roll No     Name   Age  Marks Department Admission_Date
0      101  Prithvi  20.0   89.0        CSE     01-06-2025
1      102   Akshay  20.5   87.0       ENTC     23-03-2025
2      103      Raj  21.0   90.0         IT     07-07-2025
3      104     Diya  23.0   89.5       MECH     14-06-2025
4      105      Sam  18.0   95.0        CSE     26/10/2025

In [ ]:
#Step6: Convert Admission_Date to standard datetime format
df["Admission_Date"]=pd.to_datetime(df["Admission_Date"],errors='coerce')
df

   Roll No     Name   Age  Marks Department Admission_Date
0      101  Prithvi  20.0   89.0        CSE     2025-01-06
1      102   Akshay  20.5   87.0       ENTC            NaT
2      103      Raj  21.0   90.0         IT     2025-07-07
3      104     Diya  23.0   89.5       MECH            NaT
4      105      Sam  18.0   95.0        CSE            NaT

In [ ]:
# Step7: Print clean data
print("\nCleanedData:")
df

CleanedData:

   Roll No     Name   Age  Marks Department Admission_Date
0      101  Prithvi  20.0   89.0        CSE     2025-01-06
1      102   Akshay  20.5   87.0       ENTC            NaT
2      103      Raj  21.0   90.0         IT     2025-07-07
3      104     Diya  23.0   89.5       MECH            NaT
4      105      Sam  18.0   95.0        CSE            NaT

In [ ]:
#Step8: Save the cleaned data
df.to_csv("cleaned_student_data.csv",index=False)
print("\nCleaned CSV file saved as cleaned_student_data.csv")

Cleaned CSV file saved as cleaned_student_data.csv

In [ ]:
# Do Commands on Cars93 Data
import pandas as pd
import numpy as np
df=pd.read_csv('/content/Cars93.csv')
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [ ]:
df.isna().sum()

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           34
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room      11
dtype: int64

In [ ]:
df['Luggage.room'].mean()

np.float64(13.890243902439025)

In [ ]:
df=pd.read_csv('/content/Cars93.csv')
df.isna().sum()
df['Luggage.room'].fillna(value=df['Luggage.room'].median())
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [ ]:
df['Rear.seat.room'].mean()

np.float64(27.82967032967033)

In [ ]:
df['Rear.seat.room'].fillna(value=df['Rear.seat.room'].median())

0     26.5
1     30.0
2     28.0
3     31.0
4     27.0
      ...
88    34.0
89    31.5
90    26.0
91    29.5
92    30.0
Name: Rear.seat.room, Length: 93, dtype: float64

In [ ]:
df['AirBags'].mode() #mode gives most frequently used value

0    Driver only
Name: AirBags, dtype: object

In [ ]:
df['AirBags'].fillna(value=df['AirBags'].mode())

0            Driver only
1     Driver & Passenger
2            Driver only
3     Driver & Passenger
4            Driver only
             ...
88                   NaN
89                   NaN
90                   NaN
91           Driver only
92    Driver & Passenger
Name: AirBags, Length: 93, dtype: object